# Generated by Django 4.1.3 on 2022-11-30 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "cluster_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("cluster_type", models.CharField(max_length=20)),
                ("kubeconfig", models.FileField(null=True, upload_to="")),
                ("cluster_url", models.TextField()),
                ("user_id", models.CharField(max_length=100)),
                ("insert_date", models.DateTimeField(auto_now_add=True)),
                ("bearer_token", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AppInfo",
            fields=[
                (
                    "app_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("namespace", models.CharField(max_length=100)),
                ("repo_url", models.TextField()),
                ("target_revision", models.TextField()),
                ("target_path", models.TextField()),
                ("insert_user", models.CharField(max_length=100)),
                ("insert_at", models.DateTimeField(auto_now_add=True)),
                ("update_user", models.CharField(max_length=100)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="app.cluster"
                    ),
                ),
            ],
        ),
    ]
