# Generated by Django 4.1.3 on 2022-11-30 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppDeployHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.CharField(max_length=100)),
                ("deploy_type", models.CharField(max_length=5)),
                ("user", models.CharField(max_length=100)),
                ("manager_user", models.CharField(max_length=100)),
                ("insert_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="app.appinfo"
                    ),
                ),
            ],
        ),
    ]
