# Generated by Django 4.1.3 on 2022-12-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appdeployhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='auto_create_ns',
            field=models.BooleanField(default=False, verbose_name='네임스페이스 생성'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='app_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='APP 이름'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='cluster_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.cluster', verbose_name='클러스터 이름'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='namespace',
            field=models.CharField(max_length=100, verbose_name='네임스페이스'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='repo_url',
            field=models.CharField(max_length=200, verbose_name='레파지토리 주소'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='target_path',
            field=models.CharField(max_length=100, verbose_name='레파지토리 경로'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='target_revision',
            field=models.CharField(max_length=100, verbose_name='타겟 브랜치'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='bearer_token',
            field=models.TextField(verbose_name='쿠버네티스 계정 토큰'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cluster_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='클러스터 이름'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='kubeconfig',
            field=models.FileField(null=True, upload_to='', verbose_name='kubeconfig 파일'),
        ),
    ]
